name: inqlik_cli
version: 2.0.0
author: Vadim Tsushko <vadimtsushko@gmail.com>
description: InQlik command line interface tools. Set of command line tools supporting QlikView development process
homepage: https://github.com/inqlik/inqlik_cli
dependencies:
  args: '1.5.1'
  collection: ^1.14.11
  csv: ^4.0.0
  meta: ^1.1.7
  path: ^1.6.2
  petitparser:  ^1.7.7
#  petitparser: ^2.2.1
  xml: ^3.0.1
#  dart_qv:
#    path: ../dart_qv
dev_dependencies:
  test: any
executables:
  inqlik: null
