name: inqlik_cli
version: 1.2.2-dev
author: Vadim Tsushko <vadimtsushko@gmail.com>
description: InQlik command line interface tools. Set of command line tools supporting QlikView development process
homepage: https://github.com/inqlik/inqlik_cli
dependencies:
  args: '>=0.13.4+2'
  collection: '>=1.8.0'
  csv: '>=2.0.1'
  meta: '>=0.12.1'
  path: '>=1.3.0 <2.0.0'
  petitparser: '>=1.5.3 <2.0.0'
  xml: '>=2.4.3'
#  dart_qv:
#    path: ../dart_qv
dev_dependencies:
  test: any
executables:
  inqlik: null
