name: inqlik_cli
version: 1.2.2-dev
author: Vadim Tsushko <vadimtsushko@gmail.com>
description: InQlik command line interface tools. Set of command line tools supporting QlikView development process
homepage: https://github.com/inqlik/inqlik_cli
dependencies:
  args: '>=0.12.1 <0.13.0'
  collection: any
  csv: any
  meta: '>=0.8.8 <0.9.0'
  path: '>=1.3.0 <2.0.0'
  petitparser: '>=1.2.2 <2.0.0'
  xml: any
  dart_qv:
    path: ../dart_qv
dev_dependencies:
  test: any
executables:
  inqlik: null
