name: qvs
version: 1.1.6
author: Vadim Tsushko <vadimtsushko@gmail.com>
description: A sample command-line application
homepage: https://github.com/vadimtsushko/qvs_parser
dependencies:
  args: '>=0.12.1 <0.13.0'
  collection: any
  csv: any
  meta: '>=0.8.8 <0.9.0'
  path: '>=1.3.0 <2.0.0'
  petitparser: '>=1.2.2 <2.0.0'
  xml: any
dev_dependencies:
  unittest: any
