name: qvs_parser
version: 0.0.3
author: Vadim Tsushko <vadimtsushko@gmail.com>
description: A sample command-line application
homepage: https://github.com/vadimtsushko/qvs_parser
dependencies:
  petitparser: any
  meta: any
dev_dependencies:
  unittest: any

#dependencies:
#  unittest: any